import React from "react";
import { Link } from "react-router-dom";
import "../CSS/Home.css";
import pica from "../image/pica.png";
import picb from "../image/picb.png";
import picc from "../image/picc.png";
import logo from "../image/logo.png"; 

function Home() {
  return (
    <div className="vengence">
      <div className="website">
        <div className="nava">
          <div className="logo-container">
            <div className="blue-circle"></div>
            <img src={logo} alt="Logo" className="logo-image" />
            <span className="logo-text">BookAI</span>
          </div>
          <div>Features</div>
          <div>How It Works</div>
          <div>Roadmap</div>
          <div>API</div>
          <div><Link to="/price">Price</Link></div>
          <div>Models</div>
          <div className="btn btn-danger">Login/Signup</div>
        </div>

        <div className="navb">
          <h1>
            Explore the Possibilities of <span id="text">AI Book Writing</span>{" "}
            with<br /> BookAI
          </h1>
          <p id="texta">
            Unleash the power of AI to create captivating books in minutes.
            <br /> Download, Distribute wherever you want. Generate unlimited
            free<br /> books
          </p>
          <div>
            <button className="navc">Get Started</button>
            <button className="navc">Get API Access</button>
          </div>
          <p id="textb">
            Attention: TryBookAI has been acquired by Indicus AI. Indicus LLM will
            be used for text and image generation
          </p>
        </div>

        <div className="card">
          <div className="navd">
            <i className="fas fa-robot icon"></i>
            <h4>AI-Powered Writing</h4>
            <p>Generate high-quality content with advanced AI technology.</p>
          </div>
          <div className="navd">
            <i className="fas fa-book icon"></i>
            <h4>AI-Powered Writing</h4>
            <p>Generate high-quality content with advanced AI technology.</p>
          </div>
          <div className="navd">
            <i className="fas fa-download icon"></i>
            <h4>AI-Powered Writing</h4>
            <p>Generate high-quality content with advanced AI technology.</p>
          </div>
          <div className="navd">
            <i className="fas fa-language icon"></i>
            <h4>AI-Powered Writing</h4>
            <p>Generate high-quality content with advanced AI technology.</p>
          </div>
        </div>

        <h2 id="textc">Sample Books Generated by BookAI</h2>
        <h3 id="textd">
          Explore some of the captivating books created using our AI technology.
        </h3>

        <div className="navf">
          <div className="nave">
            <img src={pica} alt="pica" className="pics" />
            <h4 className="texte">Science Fiction</h4>
            <p className="textf">
              "As Dr. Elara stepped through<br /> the shimmering portal, she{" "}
              <br /> knew there was no turning <br /> back. The fate of two
              universes <br /> now rested in her hands..."
            </p>
            <p className="textg">Read More...</p>
          </div>
          <div className="nave">
            <img src={picb} alt="picb" className="pics" />
            <h4 className="texte">Science Fiction</h4>
            <p className="textf">
              "As Dr. Elara stepped through<br /> the shimmering portal, she{" "}
              <br /> knew there was no turning <br /> back. The fate of two
              universes <br /> now rested in her hands..."
            </p>
            <p className="textg">Read More...</p>
          </div>
          <div className="nave">
            <img src={picc} alt="picc" className="pics" />
            <h4 className="texte">Science Fiction</h4>
            <p className="textf">
              "As Dr. Elara stepped through<br /> the shimmering portal, she{" "}
              <br /> knew there was no turning <br /> back. The fate of two
              universes <br /> now rested in her hands..."
            </p>
            <p className="textg">Read More...</p>
          </div>
        </div>

        <div className="container">
          <div className="texth">
            <h2>Stay Updated</h2>
            <h4>Subscribe to our newsletter for the latest AI writing tips and BookAI updates.</h4>
          </div>
          <div className="input-container">
            <input type="text" placeholder="Enter Your Email" className="textin" />
            <button className="textbtn">Subscribe</button>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Home;
